# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="A configurable set of panels that display various debug information about the current request/response."
HOMEPAGE="http://robhudson.github.com/django-debug-toolbar/"
SRC_URI="http://pypi.python.org/packages/source/d/django-debug-toolbar/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

