# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils subversion eutils

DESCRIPTION="Generic tagging application for Django"
HOMEPAGE="http://code.google.com/p/django-tagging/"
SRC_URI=""

REVISION=156
ESVN_REPO_URI="http://django-tagging.googlecode.com/svn/trunk/@${REVISION}"
LICENSE="BSD-2"
KEYWORDS="x86"
SLOT="0"
IUSE=""
DEPEND=""

src_unpack() {
    subversion_src_unpack
    cd "${S}"
    epatch "${FILESDIR}"/dt021_156-calculate_cloud_fix.patch
    epatch "${FILESDIR}"/tagged_item-subquery_fix.patch
}
