# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils subversion


DESCRIPTION="Plugin for spam filtering"
HOMEPAGE="http://trac.edgewall.org/wiki/SpamFilter"
ESVN_REPO_URI="http://svn.edgewall.com/repos/trac/sandbox/spam-filter"
LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

