# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="Easily manage your dotfiles"
HOMEPAGE="https://github.com/iElectric/g-pypi"
SRC_URI="http://pypi.python.org/packages/source/d/dotfiles/${P}.tar.gz"

LICENSE="ISC"
KEYWORDS="amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="${DEPEND}"


