# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="Python bindings for libshout 2."
HOMEPAGE="http://www.icecast.org"
SRC_URI="http://downloads.us.xiph.org/releases/libshout/${P}.tar.gz"
LICENSE="LGPL2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="media-libs/libshout"

