# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="5"
PYTHON_MODNAME="ibidem"

inherit distutils


DESCRIPTION="Ibidem Django utilities"
HOMEPAGE="http://ibidem.homeip.net/Misc/wiki/Django/Utils"
SRC_URI="http://pypi.python.org/packages/source/i/ibidem-django-util/${P}.zip"
LICENSE="LGPL-2.1"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="app-arch/unzip
	dev-python/setuptools"

