# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="High-level FTP client library (virtual filesystem and more)"
HOMEPAGE="http://ftputil.sschwarzer.net/"
SRC_URI="http://ftputil.sschwarzer.net/trac/attachment/wiki/Download/${P}.tar.gz?format=raw"
LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
S="${WORKDIR}"

# The downloaded file has the wrong name, so we rename it to something more suitable before unpacking
# The unpacked files wind up in a extra directory, so we move the workdir to match
src_unpack() {
        mv ${S}/../distdir/${A} ${S}/../distdir/${P}.tar.gz
        export A=${P}.tar.gz
	distutils_src_unpack
        export S=${S}/${P}
}
