# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

# Warning: Invalid LICENSE.
inherit distutils


DESCRIPTION="superlance plugins for supervisord"
HOMEPAGE="http://supervisord.org"
SRC_URI="http://pypi.python.org/packages/source/s/superlance/${P}.tar.gz"
LICENSE="UNKNOWN"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND="dev-python/setuptools
	app-admin/supervisor"

