# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

DESCRIPTION="An implementation of ICMP ping in Python"
HOMEPAGE="http://bitbucket.org/delroth/python-ping/"
SRC_URI="http://bitbucket.org/delroth/python-ping/downloads/${P}.tar.gz"
LICENSE="GPL-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
S=${WORKDIR}/ping-${PV}

