# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="Robots exclusion application for Django, complementing Sitemaps."
HOMEPAGE="http://bitbucket.org/jezdez/django-robots/"
SRC_URI="http://pypi.python.org/packages/source/d/django-robots/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

