# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="A Django app for managing robots.txt files following the robots exclusion protocol."
HOMEPAGE="http://bitbucket.org/jezdez/django-robots/"
SRC_URI="http://bitbucket.org/jezdez/django-robots/downloads/${P}.tar.gz"
DOCS="INSTALL.txt LICENSE.txt README.rst docs/*"

LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
