# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/pycuda/pycuda-9999.ebuild,v 1.4 2010/02/08 17:24:43 spock Exp $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="5"

inherit git-r3 distutils

EGIT_REPO_URI="git://github.com/mintchaos/django_compressor.git"

DESCRIPTION="Compresses linked and inline javascript or CSS into a single cached file."
HOMEPAGE="http://github.com/mintchaos/django_compressor"

DOCS="AUTHORS LICENSE README.rst"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

RDEPEND="dev-python/beautifulsoup"
DEPEND="${RDEPEND}"

src_unpack() {
        git_src_unpack
}

src_install() {
        distutils_src_install
}

