# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

PYTHON_MODNAME="pip"

inherit distutils


DESCRIPTION="pip installs packages.  Python packages.  An easy_install replacement"
HOMEPAGE="http://pip.openplans.org"
SRC_URI="http://pypi.python.org/packages/source/p/pip/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

