# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils


DESCRIPTION="A django application that displays the load and some other statistics about your memcached instances in the admin."
HOMEPAGE="http://github.com/bartTC/django-memcache-status"
SRC_URI="http://pypi.python.org/packages/source/d/django-memcache-status/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

