# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="MATTN"

inherit perl-module

DESCRIPTION="check that a library is available"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="x86"
IUSE=""

DEPEND=">=perl-gcpan/IO-CaptureOutput-1.1102
	dev-lang/perl"
