# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

# Warning: Invalid LICENSE.
inherit distutils


DESCRIPTION="A simple, shell based tvrss.net torrent downloader."
HOMEPAGE="http://pytvshows.sourceforge.net/"
SRC_URI="http://pypi.python.org/packages/source/p/pytvshows/${P}.zip"
LICENSE="UNKNOWN"
KEYWORDS="~x86"
SLOT="0"
IUSE=""
DEPEND="app-arch/unzip"

src_unpack() {
        unpack ${A}
        cd ${S}
        epatch "${FILESDIR}/feedurl.patch"
}
